# Generated by Django 5.2.2 on 2025-07-18 18:06

import api.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('deck', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.Card), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lvl', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('upgradePoints', models.IntegerField()),
                ('selectedCharacter', models.IntegerField()),
                ('cards', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.Card), blank=True, null=True)),
                ('characters', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model=api.models.Character), blank=True, null=True)),
                ('friends', django_mongodb_backend.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
            ],
        ),
    ]
