# Generated by Django 5.2.2 on 2025-07-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='cards',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='baseHP',
            new_name='hp',
        ),
    ]
