# Generated by Django 5.2.2 on 2025-07-18 18:39

import api.models
import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='deck',
            field=django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model=api.models.Card, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cards',
            field=django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model=api.models.Card, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='characters',
            field=django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model=api.models.Character, null=True),
        ),
    ]
