# Generated by Django 5.2.2 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_card_id_alter_character_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.IntegerField(),
        ),
    ]
